{% set version = "0.1.0" %}

package:
  name: args
  version: {{ version }}

source:
  fn: args-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/args/args-{{ version }}.tar.gz
  md5: 66faf79ba2511def7b8b81d542482046

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - args

about:
  home: https://github.com/kennethreitz/args
  license: BSD 3-clause
  summary: 'Command Arguments for Humans.'

extra:
  recipe-maintainers:
    - ericdill
    - janschulz
    - SylvainCorlay
