{% set version = "0.1.0" %}

package:
  name: args
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/args/args-{{ version }}.tar.gz
  md5: 66faf79ba2511def7b8b81d542482046

build:
  number: 1002
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - args

about:
  home: https://github.com/kennethreitz/args
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Command Arguments for Humans'

extra:
  recipe-maintainers:
    - ericdill
    - SylvainCorlay
